name: Check commit message

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Check commit message
        run: |
          python -m pip install -U pip commitizen
          cz check -m "$(git show -s --format=%s)"
